version: '3.8'

services:
  mysql55:
    image: mysql:5.5
    container_name: mysql55
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql5_data:/var/lib/mysql
    networks:
      - mysql_network

  mysql8:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306" # Expose MySQL 8.0 on port 3306
    volumes:
      - mysql8_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql5_data:
  mysql8_data:

networks:
  mysql_network:
